services:
  postgres:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: techsupport_postgres
    restart: always
    environment:
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./docker/postgres-init:/docker-entrypoint-initdb.d:ro
  postgres_backup:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: techsupport_postgres_backup
    restart: always
    environment:
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: backupdb
    ports:
      - "5440:5432"
    volumes:
      - pgdata_backup:/var/lib/postgresql
      - ./docker/postgres-init:/docker-entrypoint-initdb.d:ro

  rabbitmq:
    image: rabbitmq:3-management
    container_name: techsupport_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  redis:
    image: redis:latest
    container_name: techsupport_redis
    ports:
      - "6379:6379"
  
volumes:
  pgdata:
  pgdata_backup: