<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
    <PackageReference Include="MassTransit" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0" PrivateAssets="all" />
    <PackageReference Include="Pgvector" Version="0.3.1" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" Version="0.2.2" />
    <!-- <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" /> -->
    <PackageReference Include="Google.Cloud.AIPlatform.V1" Version="3.59.0" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.79.0" />
    <PackageReference Include="OpenAI" Version="2.13.0" />
    <PackageReference Include="QuestPDF" Version="2026.9.1" />
    <PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.21" />



  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Operation.Contracts\Operation.Contracts.csproj" />
    <ProjectReference Include="..\Technician.Contracts\Technician.Contracts.csproj" />
    <ProjectReference Include="..\Stock.Contracts\Stock.Contracts.csproj" />
    <ProjectReference Include="..\Accounting.Contracts\Accounting.Contracts.csproj" />
    <ProjectReference Include="..\Customer.Contracts\Customer.Contracts.csproj" />
    <ProjectReference Include="..\Hr.Contracts\Hr.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
