<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TechSupport.Identity</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Shared/Shared.csproj" />
    <ProjectReference Include="../User/User.csproj" />
    <ProjectReference Include="../Identity.Contracts/Identity.Contracts.csproj" />
    <ProjectReference Include="../Technician.Contracts/Technician.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="MassTransit" Version="8.0.7" />
  </ItemGroup>

</Project>
