<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TechSupport.Technician</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Identity.Contracts/Identity.Contracts.csproj" />
    <ProjectReference Include="../User.Contracts/User.Contracts.csproj" />
    <ProjectReference Include="../Technician.Contracts/Technician.Contracts.csproj" />
    <ProjectReference Include="../Operation.Contracts/Operation.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.21" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
    <PackageReference Include="MassTransit" Version="8.0.7" />
  </ItemGroup>

</Project>
