FROM nginx:stable-alpine

# build edilmiş web dosyalarını kopyala
COPY build/web /usr/share/nginx/html

# nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]