<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TechSupport.Customer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Identity.Contracts/Identity.Contracts.csproj" />
    <ProjectReference Include="../User.Contracts/User.Contracts.csproj" />
    <ProjectReference Include="../Device.Contracts/Device.Contracts.csproj" />
    <ProjectReference Include="../Customer.Contracts/Customer.Contracts.csproj" />
    <ProjectReference Include="../Operation.Contracts/Operation.Contracts.csproj" />
    <ProjectReference Include="../Trade.Contracts/Trade.Contracts.csproj" />
  </ItemGroup>  

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
    <PackageReference Include="MassTransit" Version="8.0.7" />
  </ItemGroup>

</Project>
