<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TechSupport.Trade</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Trade.Contracts/Trade.Contracts.csproj" />
    <ProjectReference Include="../Accounting.Contracts/Accounting.Contracts.csproj" />
    <ProjectReference Include="../Customer.Contracts/Customer.Contracts.csproj" />
    <ProjectReference Include="../Device.Contracts/Device.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.0.7" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
