// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.HR.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.HR.Migrations
{
    [DbContext(typeof(HRDbContext))]
    partial class HRDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hr")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.HR.Domain.Advance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId", "EmployeeId", "CreatedAtUtc");

                    b.HasIndex("TenantId", "BranchId", "DepartmentId", "CreatedAtUtc");

                    b.ToTable("Advances", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckInTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CheckOutTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlannedEndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlannedStartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ShiftAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShiftAssignmentId");

                    b.HasIndex("TenantId", "ShiftAssignmentId")
                        .IsUnique();

                    b.HasIndex("TenantId", "BranchId", "ShiftDate", "EmployeeId");

                    b.ToTable("AttendanceRecords", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.Bordro.BordroComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BranchId", "Code")
                        .IsUnique();

                    b.ToTable("BordroComponents", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.Bordro.BordroDonem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TenantId", "BranchId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("BordroDonems", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.Bordro.BordroEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BordroDonemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalEarnings")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BordroDonemId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DepartmentId1");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId", "EmployeeId");

                    b.ToTable("BordroEmployees", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.Bordro.BordroKalem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("BordroComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BordroEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("BordroComponentId");

                    b.HasIndex("BordroEmployeeId");

                    b.HasIndex("TenantId", "BranchId", "BordroEmployeeId", "CreatedAtUtc");

                    b.ToTable("BordroKalems", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Departments", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Disciplines", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.DisciplineEmployeeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DisciplineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("DisciplineEmployeeRecords", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("JobsEndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("JobsStartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex("TenantId", "DepartmentId");

                    b.HasIndex("TenantId", "EmployeeNo")
                        .IsUnique();

                    b.HasIndex("TenantId", "PositionId");

                    b.HasIndex("TenantId", "BranchId", "Status");

                    b.ToTable("Employees", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.EmployeeSalary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId", "EmployeeId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("EmployeeSalaries", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.Leave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LeaveDeductionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveDeductionId");

                    b.HasIndex("TenantId", "BranchId", "DepartmentId", "StartDate");

                    b.HasIndex("TenantId", "EmployeeId", "StartDate", "EndDate");

                    b.ToTable("Leaves", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.LeaveDeduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeductionAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("DeductionPeriod")
                        .HasColumnType("integer");

                    b.Property<int?>("DeductionType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BranchId", "CreatedAtUtc");

                    b.ToTable("LeaveDeductions", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Positions", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal>("RewardAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Rewards", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.RewardEmployeeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RewardDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RewardId");

                    b.ToTable("RewardEmployeeRecords", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.ShiftAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlannedEndTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PlannedStartTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ShiftTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ShiftTemplateId");

                    b.HasIndex("TenantId", "BranchId", "EmployeeId", "ShiftTemplateId", "ShiftDate", "PlannedStartTimeUtc")
                        .IsUnique();

                    b.ToTable("ShiftAssignments", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.ShiftTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNightShift")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BranchId", "Name")
                        .IsUnique();

                    b.ToTable("ShiftTemplates", "hr");
                });

            modelBuilder.Entity("TechSupport.Hr.Domain.AdvanceSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowFutureAdvances")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxAdvanceAmountPerPerson")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MaxAdvanceCountPerYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "BranchId")
                        .IsUnique();

                    b.ToTable("AdvanceSettings", "hr");
                });

            modelBuilder.Entity("TechSupport.Hr.Domain.EmployeePerformanceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("LeaveCount")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("NotJoinedShiftCount")
                        .HasColumnType("integer");

                    b.Property<int>("OvertimeCount")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyCount")
                        .HasColumnType("integer");

                    b.Property<int>("RewardCount")
                        .HasColumnType("integer");

                    b.Property<int>("ShiftAttendanceCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalAssignedTasks")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalCompletedLate")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalCompletedOnTime")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCompletedTasks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOverdueTasks")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPendingTasks")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId", "EmployeeId", "Year", "Month")
                        .IsUnique();

                    b.ToTable("EmployeePerformanceReports", "hr");
                });

            modelBuilder.Entity("Modules.HR.Domain.Advance", b =>
                {
                    b.HasOne("Modules.HR.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Modules.HR.Domain.Employee", "Employee")
                        .WithMany("EmployeeAdvances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Modules.HR.Domain.AttendanceRecord", b =>
                {
                    b.HasOne("Modules.HR.Domain.ShiftAssignment", null)
                        .WithMany()
                        .HasForeignKey("ShiftAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.HR.Domain.Bordro.BordroDonem", b =>
                {
                    b.HasOne("Modules.HR.Domain.Department", null)
                        .WithMany("BordroDonems")
                        .HasForeignKey("DepartmentId");
                });

            modelBuilder.Entity("Modules.HR.Domain.Bordro.BordroEmployee", b =>
                {
                    b.HasOne("Modules.HR.Domain.Bordro.BordroDonem", "BordroDonem")
                        .WithMany("BordroEmployees")
                        .HasForeignKey("BordroDonemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Modules.HR.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Modules.HR.Domain.Department", null)
                        .WithMany("BordroEmployees")
                        .HasForeignKey("DepartmentId1");

                    b.HasOne("Modules.HR.Domain.Employee", "Employee")
                        .WithMany("BordroEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("BordroDonem");

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Modules.HR.Domain.Bordro.BordroKalem", b =>
                {
                    b.HasOne("Modules.HR.Domain.Bordro.BordroComponent", "BordroComponent")
                        .WithMany("BordroKalems")
                        .HasForeignKey("BordroComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.HR.Domain.Bordro.BordroEmployee", "BordroEmployee")
                        .WithMany("BordroKalems")
                        .HasForeignKey("BordroEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BordroComponent");

                    b.Navigation("BordroEmployee");
                });

            modelBuilder.Entity("Modules.HR.Domain.DisciplineEmployeeRecord", b =>
                {
                    b.HasOne("Modules.HR.Domain.Discipline", "Discipline")
                        .WithMany("DisciplineEmployeeRecords")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Modules.HR.Domain.Employee", "Employee")
                        .WithMany("DisciplineEmployeeRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Modules.HR.Domain.Employee", b =>
                {
                    b.HasOne("Modules.HR.Domain.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Modules.HR.Domain.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Modules.HR.Domain.EmployeeSalary", b =>
                {
                    b.HasOne("Modules.HR.Domain.Employee", "Employee")
                        .WithMany("EmployeeSalaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Modules.HR.Domain.Leave", b =>
                {
                    b.HasOne("Modules.HR.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Modules.HR.Domain.Employee", "Employee")
                        .WithMany("EmployeeLeaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Modules.HR.Domain.LeaveDeduction", "LeaveDeduction")
                        .WithMany("Leaves")
                        .HasForeignKey("LeaveDeductionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("LeaveDeduction");
                });

            modelBuilder.Entity("Modules.HR.Domain.RewardEmployeeRecord", b =>
                {
                    b.HasOne("Modules.HR.Domain.Employee", "Employee")
                        .WithMany("RewardEmployeeRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Modules.HR.Domain.Reward", "Reward")
                        .WithMany("RewardEmployeeRecords")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("Modules.HR.Domain.ShiftAssignment", b =>
                {
                    b.HasOne("Modules.HR.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.HR.Domain.ShiftTemplate", "ShiftTemplate")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ShiftTemplateId");

                    b.Navigation("Employee");

                    b.Navigation("ShiftTemplate");
                });

            modelBuilder.Entity("TechSupport.Hr.Domain.EmployeePerformanceReport", b =>
                {
                    b.HasOne("Modules.HR.Domain.Employee", "Employee")
                        .WithMany("EmployeePerformanceReports")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Modules.HR.Domain.Bordro.BordroComponent", b =>
                {
                    b.Navigation("BordroKalems");
                });

            modelBuilder.Entity("Modules.HR.Domain.Bordro.BordroDonem", b =>
                {
                    b.Navigation("BordroEmployees");
                });

            modelBuilder.Entity("Modules.HR.Domain.Bordro.BordroEmployee", b =>
                {
                    b.Navigation("BordroKalems");
                });

            modelBuilder.Entity("Modules.HR.Domain.Department", b =>
                {
                    b.Navigation("BordroDonems");

                    b.Navigation("BordroEmployees");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Modules.HR.Domain.Discipline", b =>
                {
                    b.Navigation("DisciplineEmployeeRecords");
                });

            modelBuilder.Entity("Modules.HR.Domain.Employee", b =>
                {
                    b.Navigation("BordroEmployees");

                    b.Navigation("DisciplineEmployeeRecords");

                    b.Navigation("EmployeeAdvances");

                    b.Navigation("EmployeeLeaves");

                    b.Navigation("EmployeePerformanceReports");

                    b.Navigation("EmployeeSalaries");

                    b.Navigation("RewardEmployeeRecords");
                });

            modelBuilder.Entity("Modules.HR.Domain.LeaveDeduction", b =>
                {
                    b.Navigation("Leaves");
                });

            modelBuilder.Entity("Modules.HR.Domain.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Modules.HR.Domain.Reward", b =>
                {
                    b.Navigation("RewardEmployeeRecords");
                });

            modelBuilder.Entity("Modules.HR.Domain.ShiftTemplate", b =>
                {
                    b.Navigation("ShiftAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
